version: "2"

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  api:
    restart: always
    image: api
    build: ./build/api
    container_name: api
    environment:
      - VIRTUAL_HOST=api.kinokabaret.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.kinokabaret.com
      - LETSENCRYPT_EMAIL=support@kinokabaret.com

  website:
    restart: always
    image: website
    build: ./build/website
    container_name: website
    volumes:
      - "./volumes/nginx-website/conf.d/:/etc/nginx/conf.d"
      - "./volumes/config/website/config.js:/usr/share/nginx/html/config.js"
    environment:
      - VIRTUAL_HOST=kinokabaret.com,www.kinokabaret.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=kinokabaret.com
      - LETSENCRYPT_EMAIL=support@kinokabaret.com

  gitlab:
    restart: always
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'gitlab.kinokabaret.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.kinokabaret.com:30080'
        gitlab_rails['gitlab_shell_ssh_port'] = 30022
    ports:
      - '30443:443'   #didn't find the way to enable both http ports
      - '30080:30080'
      - '30022:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
